print("=====Simple calculator=====")
x=int(input("Enter the first number:"))
print("first number:",x)
y=int(input("Enter the second number:"))
print("second number:",y)
print("Addition:",x+y)
print("Substraction:",x-y)
print("Multiplication:",x*y)
print("Division:",x/y)
print("Modules:",x%y)