print("************Student Id Card**********")
name=input("Enter student name:")
# how to emoji create (window+.) click the button
print("👤 Name:",name)
rollno=input("Enter roll no:")
print("🆔 Roll no:",rollno)
college=input("Enter the college name:")
print("🏫 college:",college)
branch=input("Enter Branch:")
print("💻 Branch:",branch)
semester=input("Enter Semester:")
print("📚 Semester:",semester)
phoneno=int(input("Enter the phone number:"))
print("📞 Phone no:",phoneno)